name: Disable Jekyll Build

on:
  push:
    branches: [ main ]

jobs:
  disable-jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create .nojekyll file
        run: |
          touch .nojekyll
          echo "This file disables Jekyll processing" > .nojekyll
      
      - name: Commit .nojekyll
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .nojekyll
          git commit -m "Add .nojekyll to disable Jekyll" || echo "No changes to commit"
          git push 